project:
  type: website
  resources:
    - assets/**

execute:
  freeze: auto

website:
  title: "Ivan Ricardo"
  navbar:
    background: "#2d3561"
    search: true
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - text: Posts
        href: posts.qmd
      - text: Software
        href: software.qmd
      - publications.qmd
    tools:
      - icon: github
        href: https://github.com/ivanuricardo
        menu:
          - text: Source Code
            url: https://github.com/ivanuricardo/ivanuricardo.github.io
          - text: Report a Bug
            url: https://github.com/ivanuricardo/ivanuricardo.github.io/issues

  page-footer: "Made with ❤️, Copyright 2024, Ivan U. Ricardo"
format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: false



