---
title: "Software"
title-block-banner: assets/farren-misty.png
title-block-banner-color: "#100c08"
---

<style>

main {
    z-index: 100;
}

#title-block-header {
  margin-block-end: -25rem;
  position: relative;
  margin-top: 1px;
  height: 800px;
}

.quarto-title-banner {
  margin-block-end: 1rem;
  position: relative;
  margin-top: -10px;
  height: 85%;
}

</style>


## [MatrixAutoRegressions.jl](https://github.com/ivanuricardo/MatrixAutoRegressions.jl)
A lightweight Julia package for Matrix Autoregressive (MAR) models.

## [GraphicalLasso.jl](https://github.com/ivanuricardo/GraphicalLasso.jl)

This package provides efficient tools for generating sparse covariance matrices, estimating sparse precision matrices using the graphical lasso (glasso) algorithm (Friedman, Hastie, and Tibshirani 2008; Meinshausen and Bühlmann 2006), and selecting optimal regularization parameters.

## [Rank Determination in Matrix Error Correction Models](https://github.com/ivanuricardo/MECMrankdetermination)

Replication materials for "Detecting Cointegrating Relations in Non-Stationary Matrix-Valued Time Series".
 

